#!/bin/bash

sudo apt -y install build-essential python3 python3-pip curl tmux xclip

# Install fzf
# if /opt/fzf already exists, pull the latest version
# else clone the repo
if [ -d "/opt/fzf" ]; then
  git -C /opt/fzf pull
else
  sudo git clone --depth 1
fi
sudo /opt/fzf/install --key-bindings --completion --no-update-rc --no-bash --no-zsh --no-fish
