#!/bin/bash

sudo apt -y install build-essential python3 python3-pip curl

sudo git clone --depth 1 https://github.com/junegunn/fzf.git /opt/fzf
sudo /opt/fzf/install --key-bindings --completion --no-update-rc --no-bash --no-zsh --no-fish

