#!/bin/bash

sudo apt -y install zsh
chsh -s $(which zsh)

if [ -d "$HOME/.oh-my-zsh" ]; then
  git -C "$HOME/.oh-my-zsh" pull
else
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# Install zsh-autosuggestions
if [ -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
  git -C "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" pull
else
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi
